functional:
- У пользователя должна быть возможность зарегистрироваться
- У пользователя должна быть возможность авторизоваться
- У незарегистрированного пользователя должна быть возможность сыграть в тестовую игру 
- Зарегистрированный пользователь должен иметь возможность видеть в лобби игроков, которые онлайн, список действующих битв и чат
- Зарегистрированный пользователь должен иметь возможность писать сообщения в чате лобби и видеть сообщения
- Зарегистрированный пользователь должен иметь возможность зайти в битву как зритель, либо на правах участника
- Зарегистрированный пользователь должен иметь возможность создать свою битву с ботом/реальным участником
- Зарегистрированный пользователь должен иметь возможность видеть список предстоящих и прошедших турниров, просматривать информацию о них, присоединяться с предстоящим, а также создавать свой турнир
- Зарегистрированный пользователь должен иметь возможность видеть историю прошедших игр, просматривать подробную информацию о них
- У каждого пользователя дожна быть страница профиля с информацией об игроке, историей игр и статистикой
- У каждого пользователя дожна быть возможность зайти в настройки и изменить имя, предпочитаемый язык программирования, звук и громкость уведомлений
- Должна быть страница рейтинга всех игроков
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
